---
title: "TweetsEDA"
author: "HanchengDai"
date: "11/17/2020"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

 
```{r}
library (rtweet)
#library (httpuv)
library(rtweet)
library(tidytext)
library(tidyverse)
```
 

```{r}
consumerKey <- "y8MbkqzEb1bbA3V0imw9gSv3E"
consumerSecret <- "S2MbeYpyCWsbKwwiNX1GoLciw7kzxSh35yXFi4PulwQ2vRxMMG"
accessToken <- "1316174107512193024-u3Y1pabNFRmlB2gD2rIV0d0smGXCU7"
accessTokenSecret <- "9nvIbe4aJ2nJ7scSRdRSCFJG83saAzOAwtoGxloFwOqC4"
``` 

```{r}
 
## authenticate via web browser
token <- create_token(
  app = "ExploreTweetRanalysis",
  consumer_key = consumerKey,
  consumer_secret = consumerSecret,
  access_token = accessToken,
  access_secret = accessTokenSecret)
```

```{r}
get_token()
```

```{r}
 tweets <- search_tweets(q = "#ClimateEmergency", 
                        n = 12000,
                        include_rts = FALSE,
                        `-filter` = "replies",
                        lang = "en")
```
```{r}
tweets %>% 
  sample_n(5) %>%
  select(created_at, screen_name, text, favorite_count, retweet_count)
```


```{r}
ts_plot(tweets, "hours") +
   labs(x = NULL, y = NULL,
       title = "Frequency of tweets with a #ClimateEmergency hashtag",
       subtitle = paste0(format(min(tweets$created_at), "%d %B %Y"), " to ", format(max(tweets$created_at),"%d %B %Y")),
       caption = "Data collected from Twitter's REST API via rtweet") +
  theme_minimal()
```

 


 
 
```{r}
th = tweets %>% 
  arrange(favorite_count) %>%
  top_n(10, favorite_count) %>%
  select(screen_name,favorite_count)
 
 
ggplot(th,aes(x = reorder(screen_name,favorite_count), y = th1$favorite_count), ) + geom_bar(stat = "identity", fill = "#bb0000", width = 0.2) + labs(x = "Username", y = "Freq", title = "Top 10 user with the highest favorite count") + geom_text(aes(label = favorite_count, hjust = "left")) 

```
 



```{r}
 
th = tweets %>% 
  count(screen_name, sort = TRUE) %>%
  top_n(10) %>%
  mutate(screen_name = paste0("@", screen_name))
 
 
 ggplot(th,aes(x = reorder(screen_name, th$n) , y = th$n), ) + geom_bar(stat = "identity", fill = "#dd0000") + labs(x= "Username", y = "Freq", title = "Top 10 Active  Users")+
   coord_flip() + geom_text(aes(label = th$n, hjust = "left"))
 
```
 


```{r}
 
th = tweets %>% 
  unnest_tokens(hashtag, text, "tweets", to_lower = FALSE) %>%
  filter(str_detect(hashtag, "^#"),
        hashtag != "#ClimateEmergency") %>%
  count(hashtag, sort = TRUE)  %>%
  top_n(10) 
 
ggplot(th1,aes( x = reorder(th$hashtag, th$n), y = th$n), ) + geom_bar(stat = "identity", fill = "#fe1f14") + labs(x = "HashTags", y = "Freq", title = "Top 10 Hashtag")+
  coord_flip() + geom_text(aes(label = th$n, hjust = "left"))
```
 
```{r}
th = tweets %>% 
  unnest_tokens(mentions, text, "tweets", to_lower = FALSE) %>%
  filter(str_detect(mentions, "^@")) %>%  
  count(mentions, sort = TRUE) %>%
  top_n(10)

ggplot(th,aes( x = reorder(th$mentions, th$n), y = th$n), ) + geom_bar(stat = "identity", fill = "#fe1f14") + labs(x = "UserNames", y = "Freq", title = "Top 10 Mentioned User")+
  coord_flip() + geom_text(aes(label = th$n, hjust = "left"))
 
```
 
```{r}
words <- tweets %>%
  mutate(text = str_remove_all(text, "&amp;|&lt;|&gt;"),
         text = str_remove_all(text, "\\s?(f|ht)(tp)(s?)(://)([^\\.]*)[\\.|/](\\S*)"),
         text = str_remove_all(text, "[^\x01-\x7F]")) %>% 
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word,
        !word %in% str_remove_all(stop_words$word, "'"),
        str_detect(word, "[a-z]"),
        !str_detect(word, "^#"),         
        !str_detect(word, "@\\S+")) %>%
  count(word, sort = TRUE)
```
 
 
```{r}
library(wordcloud) 
words %>% 
  with(wordcloud(word, n, random.order = FALSE, max.words = 100, colors = brewer.pal(8,"Dark2")))
```
 
 